image: docker:19.03-dind

services:
  - docker:19.03-dind
    # If you use insecure registry, enable below.
    # command: ["--insecure-registry", "your.registry:port"]

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  HTTPS_PROXY: $HTTPS_PROXY
  IMAGE_NAME: tkeydll/azure-stack-cli
  CLI_VERSION: 2.3.1
  # If you use insecure registry, enable below.
  # INSECURE_REGISTRY: $REGISTRY

stages:
  - build
  - notify

build_job:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$CLI_VERSION . --build-arg ca_cert_url=$CA_CERT_URL
    - docker push $REGISTRY/$IMAGE_NAME:$CLI_VERSION

notify_job:
  stage: notify
  variables:
    NOTIFY_DATA: '{"@type": "MessageCard", "themeColor": "0072C6", "title": "azure-stack-cli-docker is updated.", "text": "http://$REGISTRY/tag/$IMAGE_NAME/$CLI_VERSION/"}'
  script:
    - export HTTP_PROXY=$HTTPS_PROXY
    - export HTTPS_PROXY=$HTTPS_PROXY
    - apk add --no-cache curl
    - 'curl -X POST -H "Content-Type: application/json" --data "${NOTIFY_DATA}" $NOTIFY_URL'
